version: '3.12'
services:
  api:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: basic_app
    ports:
      - "3001:3000" 
    volumes:
      - .:/app   
    restart: unless-stopped 
    working_dir: /app       
    command: python app.py  

  console-app:
    build:
      context: . 
      dockerfile: Dockerfile
    image: console-app:latest
    container_name: console-app
    command: python app.py
    working_dir: /app
    restart: unless-stopped
